name: build

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.30.3
    with:
      build-image: true
      docker-tag: ckotzbauer/sbom-diff-action:latest
