name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS }}

      - name: Generate Changelog
        uses: ckotzbauer/changelog-generator@da2406cc87aae755ce6d2bde1aeb20ee4b5edd8f
        with:
          release-version: ${{ github.event.inputs.version }}
          github-handle: ${{ github.repository }}
          commit-output: commits.md

      - name: Push release
        uses: ckotzbauer/actions-toolkit/push-release@0.44.0
        with:
          version: ${{ github.event.inputs.version }}
          branch: main
          pat: ${{ secrets.REPO_ACCESS }}
          prerelease: ${{ contains(inputs.version, 'alpha') || contains(inputs.version, 'beta') || contains(inputs.version, 'rc') }}

      - name: Update v1 tag
        run: |
          git tag -fa v1 -m "Update v1 tag"
          git push origin v1 --force
